songs:
  - url: https://www.youtube.com/watch?v=9qoXa5_w3Gw
    title: "Sauna - Vulfpeck"
    note: "Guess all the things! Much information is stored here to make the line very long. Very long it must be.\nDoes line breaks work?"

  - url: https://youtu.be/dTnHAITmuYQ?t=51
    start: 52
  
  - url: https://www.youtube.com/watch?v=6gKZj5lLcUk&ab_channel=Vulf
  
  - url: https://www.youtube.com/watch?v=le0BLAEO93g&ab_channel=Vulf
